name: helm-upgrade
run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: 'Environment to deploy to'
        type: string
      helm-values-path:
        type: string
        default: './todoapp/values.yaml'
      helm-release-name:
        default: todoapp
        type: string


jobs:
  deploy-helm:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Download Cluster
        uses: actions/download-artifact@v4
        with:
          name: cluster-artifact

      - name: Create Cluster
        uses: helm/kind-action@v1
        with:
          config: ./cluster.yml

      - uses: actions/download-artifact@v4
        with:
          name: Helm-package
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: Helm-artifact
          path: .

      - name: Set Up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Set Up Kubectl
        uses: azure/setup-kubectl@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ vars.AZURE_CLUSTER_NAME }}

      - name: Development to Dry Run
        run: |
          helm install --dry-run ${{ inputs.helm-release-name }} ./todoapp-*.tgz \
          -f ${{ inputs.helm-values-path }} \
          --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
          --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
          --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
          --set todoapp.secrets.SECRET_KEY="${{ secrets.TODOAPP_SECRET_KEY }}" \
          --set todoapp.secrets.DB_NAME="${{ secrets.DB_NAME }}" \
          --set todoapp.secrets.DB_USER="${{ secrets.DB_USER }}" \
          --set todoapp.secrets.DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
          --set todoapp.secrets.DB_HOST="${{ secrets.DB_HOST }}" \
          --set todoapp.image.version=${{ github.sha }}

      - name: Deploy helm to ${{ inputs.environment }}
        run: |
          helm upgrade --install --atomic --wait --timeout 3600s --debug ${{ inputs.helm-release-name }} ./todoapp-*.tgz \
          -f ${{ inputs.helm-values-path }} \
          --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
          --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
          --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
          --set todoapp.secrets.SECRET_KEY="${{ secrets.TODOAPP_SECRET_KEY }}" \
          --set todoapp.secrets.DB_NAME="${{ secrets.DB_NAME }}" \
          --set todoapp.secrets.DB_USER="${{ secrets.DB_USER }}" \
          --set todoapp.secrets.DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
          --set todoapp.secrets.DB_HOST="${{ secrets.DB_HOST }}" \
          --set todoapp.image.version=${{ github.sha }}
  